CREATE TABLE IF NOT EXISTS `Refund` (`store` varchar(255),
 `sale_date` varchar(255),
 `TillID` varchar(255),
 `transaction_time` varchar(255),
 `TransactionId` varchar(255),
 `RsGlobalTxnID` varchar(255),
 `tran_tendered` float,
 `OperatorID` varchar(255),
 `item_code` varchar(255),
 `stock_cost` float,
 `soh_qty` int,
 `Quantity` int,
 `price` float,
 `discounted_price` float,
 `CardNo` varchar(255),
 `voucher_used` float,
 `PrimaryKey` varchar(255))