CREATE TABLE IF NOT EXISTS `Inv` (`store` int,
 `sale_date` varchar(255),
 `TillID` varchar(255),
 `transaction_time` varchar(255),
 `TransactionId` varchar(255),
 `GlobalTxnID` varchar(255),
 `OperatorID` varchar(255),
 `tran_tendered` float,
 `MediaType` varchar(255),
 `Tendered` float,
 `CardNo` varchar(255),
 `voucher_used` float,
 `credit_card` varchar(255),
 `PrimaryKey` varchar(255),
 `門市` varchar(255))